baseURL: 'https://biblicaldhiman.github.io/'
languageCode: 'en-us'
title: 'Rajat Dhiman'
enableRobotsTXT: true
theme: PaperMod 

params:
  theme: "dark"
  darkmode: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: Rajat Dhiman
  customCSS:
  - css/custom.css
  description: 'Rajat Dhiman, Follower of Jesus Christ in India'
  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: false
  displayFullLangName: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: false
  ShowPageNums: false
  ShowToc: false

  homeInfoParams:
    Title: "Rajat Dhiman"
    imageUrl: "https://assets.about.me/background/users/b/i/b/biblical_dhiman_1671217535_663.jpg"
    imageTitle: "Rajat Dhiman Profile picture" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    content: >
      ЁЯСЛ I am Rajat Dhiman, a born-again Christian from India.
      
      
      I run a Christian YouTube channel called тАЬBiblical DhimanтАЭ to defend and answer questions raised against Christianity, God and the Bible.
  
  
      Watch the video podcast on [YouTube](https://www.youtube.com/@BiblicalDhiman/featured).
  
  
      Listen to my audio podcast on [Spotify](https://open.spotify.com/show/2Ov2HrUlLcQWERnJifyJhs) and [Apple Podcast](https://podcasts.apple.com/us/podcast/biblical-dhiman/id1646225812).
      
      
      Connect with me on Social Media:
  socialIcons:
    - name: X
      title: Contact on Twitter
      url: "https://x.com/biblical_dhiman"
    - name: Facebook
      title: Contact on Facebook
      url: "https://www.facebook.com/dhiman.biblical"
    - name: instagram
      title: Contact on Instagram
      url: "https://www.instagram.com/irajatism"
    - name: email
      title: Contact via email
      url: "mailto:rddhiman10@gmail.com"
    - name: Spotify
      title: Listen to podcasts on Spotify
      url: "https://open.spotify.com/show/2Ov2HrUlLcQWERnJifyJhs"
    - name: YouTube
      title: Watch videos on YouTube
      url: "https://www.youtube.com/@BiblicalDhiman/featured"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/biblicaldhiman"

menu:
  main:
    - name: ABOUT ME
      weight: 100
      identifier: about
      url: /about
    - name: PODCASTS
      identifier: podcasts
      weight: 300
      url: /podcasts
    - name: CONTACT
      identifier: contact
      weight: 400
      url: /contact
    - name: RESOURCES
      identifier: resources
      weight: 500
      url: /resources

DefaultContentLanguage: 'en'
languages:
  en:
    title: 'Rajat Dhiman | Rajat Dhiman'
    languageName: ' ЁЯЗмЁЯЗз English'
    weight: 1
  hi:
    title: 'рд░рдЬрдд рдзреАрдорд╛рди | рд░рдЬрдд рдзреАрдорд╛рди'
    languageName: 'ЁЯЗоЁЯЗ│ Hindi'
    weight: 2
    params:
      homeInfoParams:
        Title: "рд░рдЬрдд рдзреАрдорд╛рди"
        Content: >
          ЁЯСЛ рдореИрдВ рд░рдЬрдд рдзреАрдорд╛рди рд╣реВрдБ, рднрд╛рд░рдд рд╕реЗ рдПрдХ рдкреБрдирд░реНрдЬрдиреНрдо рд▓реЗрдиреЗ рд╡рд╛рд▓рд╛ рдИрд╕рд╛рдИ рд╣реВрдБред 
          
          
          рдореИрдВ рдИрд╕рд╛рдИ рдзрд░реНрдо, рдИрд╢реНрд╡рд░ рдФрд░ рдмрд╛рдЗрдмрд┐рд▓ рдХреЗ рдЦрд┐рд▓рд╛рдл рдЙрдард╛рдП рдЧрдП рд╕рд╡рд╛рд▓реЛрдВ рдХрд╛ рдмрдЪрд╛рд╡ рдХрд░рдиреЗ рдФрд░ рдЙрдирдХрд╛ рдЬрд╡рд╛рдм рджреЗрдиреЗ рдХреЗ рд▓рд┐рдП "рдмрд╛рдЗрдмрд┐рд▓ рдзреАрдорд╛рди" рдирд╛рдордХ рдПрдХ рдИрд╕рд╛рдИ YouTube рдЪреИрдирд▓ рдЪрд▓рд╛рддрд╛ рд╣реВрдБред


          [YouTube](https://www.youtube.com/@BiblicalDhiman/featured) рдкрд░ рд╡реАрдбрд┐рдпреЛ рдкреЙрдбрдХрд╛рд╕реНрдЯ рджреЗрдЦреЗрдВред


          [Spotify](https://open.spotify.com/show/2Ov2HrUlLcQWERnJifyJhs), [Apple Podcast](https://podcasts.apple.com/us/podcast/biblical-dhiman/id1646225812) рдкрд░ рдореЗрд░рд╛ рдСрдбрд┐рдпреЛ рдкреЙрдбрдХрд╛рд╕реНрдЯ рд╕реБрдиреЗрдВред
          
          рд╕реЛрд╢рд▓ рдореАрдбрд┐рдпрд╛ рдкрд░ рдореБрдЭрд╕реЗ рдЬреБрдбрд╝реЗрдВ:
